{% set version = "0.2.0" %}

package:
  name: wicken
  version: {{ version }}

source:
  url: https://github.com/ioos/wicken/archive/v{{ version }}.tar.gz
  sha256: 1f74111b50b232dabecaa6940a1eab813933758e171796e65a70e7c70d6998aa

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - lxml
    - petulant-bear

test:
  imports:
    - wicken

about:
  home: https://github.com/ioos/wicken
  license:  Apache 2.0
  license_file: COPYING
  summary: 'Maps metadata concepts to concrete specifications and file formats'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
