travis:
  secure:
    BINSTAR_TOKEN: uQ2F9RmQMayL1emM2awCYTJUZJu1oXK8WAPDUFWF+EIVYcG++bGdmE3oSCmqjSaloaaR5AHRxlo/s0IgudrlDnxbya0wc3YoXcRgFH0uBb10jmUQJaHzZGDMF18Q10Hwe7IwSb9Sl/nr0atiiVPQSAbE8pWMKI0GQNIRB9ZW73zGRDYV7yWYTBQeDZMeaO5ulQaoe7EEOqY5ZxaQomPkwYfM3o6enTn2ZOOBeA0FleCdcM4tC/rfUHuylegnRJh4Fc2P3e9WnZzevsNTf/ZrGthDTjc5Ch1UKsYpUi4Gu5zbId7LGURvOyucEiGUJHMCAnevh0a39aOKnTrPhkw4L/i77FyLw3GMWz12U+gWfjmpIsFEjb+4i6NJ0zjYw5ruWr3AyUQy/LVvtOyJlYAjKRqUXPMGHyoQTmdQ2bDAeg7Vv27PYSVs9wqJHklEoVHxurYxEMYTjmgo+OrhNRWTzs1RUShUmYl/zPQ3469pu+WueXcPfRV7CyCADK6q7Sjlo5o/OlbG9wM8K9Y1h0sZcZzxs5Fbb2x+O/54iChTdFj8rJ7+1OrAP9GGE/weMmk2cAh0N0Lc8vax7uhl78nc0t18tCUxrSq+W0xEL9t9kpOyGycxzXgGFZwCvRAvcyifL8vt6uVARlMN6kF5lSJm+glAKlUGCjIbV1qFLRu1oVk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
